version: '3'

services:
  app:
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - exclude:/app/node_modules
    environment:
      - WATCHPACK_POLLING=true

volumes:
  exclude: